### ISSUE TITLE
Use `cookiecutter` for bootstrapping

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/country-template#109]
When I'm creating a new extension for my country model,
I want it to be easy as tools that I already know like [cookiecutter](https://github.com/cookiecutter/cookiecutter),
si I can spend more time adding value to users.

**Comment by MattiSG** [comment]
I'm not sure what that would entail exactly: does this mean this repository would have to become a `cookiecutter`-based template, replacing its [`bootstrap.sh`](https://github.com/openfisca/country-template/blob/master/bootstrap.sh) file with a `cookiecutter` declaration, and requiring users to install and execute `cookiecutter`?

**Comment by maukoquiroga** [comment]
Hello @MattiSG !

> does this mean this repository would have to become a `cookiecutter`-based template, replacing its [`bootstrap.sh`](https://github.com/openfisca/country-template/blob/master/bootstrap.sh) file with a `cookiecutter` declaration, and requiring users to install and execute `cookiecutter`?

Yes!

Bootstrapping a country/city would then be something like:

```
$ pip install cookiecutter
$ cookiecutter https://github.com/openfisca/country-template
organisation: segpres
country: chile
```

And then it would be iso functional —thanks to [pre/post-hooks](https://cookiecutter.readthedocs.io/en/1.7.3/advanced/hooks.html).

##### Pros

- Cross-platform, thus easier to maintain, ex: #47, #82
- [Easily testable](https://github.com/pydanny/cookiecutter-django/blob/103cc9f2ffb594796b98b2916ecec043b8b5dd9e/tests/test_cookiecutter_generation.py)
- [Template remains also testable](https://github.com/pydanny/cookiecutter-django/blob/103cc9f2ffb594796b98b2916ecec043b8b5dd9e/tests/test_bare.sh)

##### Cons

- It's a DSL —learning curve

**Comment by MattiSG** [comment]
Another con: third-party dependency.

This sounds like an interesting venue to solve #82, but also like a big investment. I would not personally invest in it for the moment considering the production experience there is with the current system, and the limited practical existing problems this seems to solve.

**Comment by maukoquiroga** [comment]
I was going to invest personally on this until some other issues took priority.

I still believe it is worth doing, maybe there are [other options](https://copier.readthedocs.io/en/latest/comparisons/) closer to what we do now that are easier to implement.

**Comment by verbman** [comment]
Did not see this thread, but thanks for pointing it out @MattiSG. Pull Request #139 does not change this conversation and possibly better prepares the way for it. I note the offline conversation also about utilising github workflows? to achieve the same objectives (but for github only).

**Comment by MattiSG** [comment]
Indeed, the reference for using GitHub Actions is https://github.com/OpenTermsArchive/demo-declarations/pull/12.

**Comment by bonjourmauko** [comment]
Thanks both @MattiSG and @verbman. I'm closing this issue as, even if the problem is still there, it is bound to a how from which I have distanced myself. I a need for a solution arises in the future, I'd rather open a new ticket.
