### ISSUE TITLE
Tests are not failing

### ISSUE THREAD

**Issue by guillett** [openfisca/country-template#8]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

I may have an issue on openfisca-france from mes-aides.gouv.fr and I wanted to test the bogus behaviour in a simpler environment.

~~The behavior I am struggling with is the aggregation of a variable (computed _on the fly_ not provided by the user) on sub-entities of a group entity. (Explicitly, I want to know if [this line](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/rsa.py#L164) will retrieve `aah` values computed on _on the fly_.)~~ I think I figured what is happening in that scenario but the issue is still relevant. :-)

However, I open this issue because a much simpler scenario is failing.

### Here is what I did:
[A commit creating a failing test.](https://github.com/guillett/country-template/commit/5b15ca2ed7c618cdc588c6738bdf699e28571a87?diff=unified)

### Here is what I expected to happen:
`make test` to fail.

### Here is what actually happened:
[Tests passed.](https://circleci.com/gh/guillett/country-template/12)

_Am I doing something wrong ?_

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
Hi @guillett,

Thanks a lot for reporting this issue. You were not doing anything wrong, there was indeed a problem with the test runner.

It should be resolved now. Please feel free to reopen this issue if it's not the case 🙂 .

**Comment by guillett** [comment]
Great! I confirm the test is not failing and it is no longer a false positive.
